name: "🐛 Bug Report"
description: Report a reproducible bug or issue.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the information below."

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Briefly describe the issue."
      placeholder: "The app crashes when I click X..."

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "What steps caused this issue?"
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs / Screenshots"
      description: "Attach logs, screenshots, or crash reports (if any)."
      render: shell
