name: "💡 Feature Request"
description: Suggest a new idea or improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for your suggestion! Please tell us more below."

  - type: input
    id: summary
    attributes:
      label: "Feature Summary"
      placeholder: "Add dark mode, improve performance, etc."
      description: "Brief summary of your idea."

  - type: textarea
    id: details
    attributes:
      label: "Detailed Description"
      description: "Describe the feature in detail and why it’s needed."
      placeholder: "It would be useful because..."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "What alternatives or workarounds have you thought about?"
